name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        V=$(cat $(dirname $0)/versions.md | grep "## " | head -n 1 | awk '{print $2}')
        T=$(git remote -v | grep 'origin' | grep '(push)' | grep 'git@github.com' | awk -v V="$V" -F '[@ :\t/\.]' '{print "docker.pkg.github.com/" $5 "/" $6 "/" $6 ":" V }')
        docker build . -t my-centos7:$T
        docker push my-centos7:$T
