name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        V=$(cat versions.md | grep "## " | head -n 1 | awk '{print $2}')
        git remote -v
        T=$(git remote -v | head -n1 | awk -v V="$V" -F '[/]' '{split($5, arr, " "); print "docker.pkg.github.com/" $4 "/" arr[1] "/" arr[1] ":" V }')
        docker build . -t $T
        docker push $T
